### ISSUE TITLE
Diff comments hard to read

### ISSUE THREAD

**Issue by pikeas** [Thertzlor/semantic-rainbow#2]
**Describe the bug**
In the source code diff view, it's difficult to read comments on newly added lines, and new comments added to existing lines.

**To Reproduce**
Add a comment and open the diff view.

**Expected behavior**
Newly added comments should be legible in diff view.

**Screenshots**
<img width="205" alt="Screen Shot 2022-10-18 at 1 05 05 PM" src="https://user-images.githubusercontent.com/686573/196509694-d3eb7387-2c81-470a-b377-aaa26c9d8828.png">

**Comment by Thertzlor** [comment]
Definitely going to include a fix for this in the next release.
I'll leave the color of the comments themselves alone, but a good way to increase the contrast seemed to be turn down the brightness of the diff background, and then slightly increasing the saturation to regain noticeability with less impact on legibility:
![image](https://user-images.githubusercontent.com/72997728/198257032-3d9f3611-c489-4ac6-b8fe-9d1329a064ef.png)

**Comment by Thertzlor** [comment]
Closing as the brighter comment color has been included in the last update.
